# Generated by Django 3.2.25 on 2026-06-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("serving", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("barcode", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="units.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Foods",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["barcode"], name="foods_food_barcode_a0aca0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["user", "brand"], name="foods_food_user_id_d68bec_idx"
            ),
        ),
    ]
