# Generated by Django 3.2.25 on 2026-06-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., 'g', 'kcal', 'mg'", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Nutrients",
            },
        ),
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="foods.food",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.nutrient"
                    ),
                ),
            ],
            options={
                "unique_together": {("food", "nutrient")},
            },
        ),
    ]
