# Generated by Django 3.2.25 on 2026-06-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0004_nutrient_abbreviation_plural"),
        ("foods", "0002_foodnutrient_nutrient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodnutrient",
            name="nutrient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nutrients.nutrient"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodnutrient",
            unique_together=set(),
        ),
    ]
