# Generated by Django 3.2.25 on 2026-06-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0006_auto_20260623_1316"),
        ("foods", "0003_auto_20260622_1716"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Nutrient",
        ),
        migrations.AlterField(
            model_name="foodnutrient",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_nutrients",
                to="foods.food",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodnutrient",
            unique_together={("food", "nutrient")},
        ),
    ]
