# Generated by Django 3.2.25 on 2026-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_auto_20260624_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="last_used_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
