# Generated by Django 3.2.25 on 2026-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalgroup",
            name="end_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goalgroup",
            name="start_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
