# Generated by Django 3.2.25 on 2026-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0002_auto_20260622_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="name_plural",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
