# Generated by Django 3.2.25 on 2026-06-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0003_alter_nutrient_name_plural"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrient",
            name="abbreviation_plural",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
