# Generated by Django 3.2.25 on 2026-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0004_nutrient_abbreviation_plural"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutrient",
            name="abbreviation_plural",
        ),
        migrations.RemoveField(
            model_name="nutrient",
            name="name_plural",
        ),
        migrations.AddField(
            model_name="nutrient",
            name="show_in_diary_total",
            field=models.BooleanField(
                default=True,
                help_text="If True, this nutrient will be visible to users",
            ),
        ),
    ]
