# Generated by Django 3.2.25 on 2026-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0005_auto_20260623_1152"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutrient",
            options={"ordering": ["order"], "verbose_name": "Nutrients"},
        ),
        migrations.AddField(
            model_name="nutrient",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
