# Generated by Django 3.2.25 on 2026-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealfood",
            old_name="amount",
            new_name="number_of_servings",
        ),
        migrations.AddField(
            model_name="mealfood",
            name="serving_size",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
