# Generated by Django 3.2.25 on 2026-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_auto_20260623_1416"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="meal",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
