# Generated by Django 3.2.25 on 2026-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "show_in_diary_total",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this nutrient will be visible to users",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Nutrients",
                "ordering": ["order"],
            },
        ),
    ]
