# Generated by Django 3.2.25 on 2026-06-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("body_metrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_metric",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
