# Generated by Django 3.2.25 on 2026-06-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_auto_20260622_1716"),
        ("groceries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grocerylist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="grocerylist",
            name="generate_from_diary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grocerylistfood",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foods.food"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grocerylistfood",
            unique_together=set(),
        ),
    ]
