# Generated by Django 3.2.25 on 2026-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="food_sort",
            field=models.CharField(
                choices=[
                    ("name", "Name"),
                    ("-created_at", "Newest"),
                    ("created_at", "Oldest"),
                ],
                default="-created_at",
                max_length=50,
            ),
        ),
    ]
