release-nightly:
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  needs: verify

  runs-on: ubuntu-latest

  permissions:
    contents: write

  # TODO Release should build more than just front end. Should be a full deployable
  # release!
  steps:
    - name: Download frontend bundle
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: frontend-dist

    - name: Create zip
      run: |
        cd frontend-dist
        zip -r ../frontend-dist.zip .

    - name: Publish nightly release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: Nightly
        prerelease: true
        make_latest: false
        replace_artifacts: true
        files: frontend-dist.zip